### ISSUE TITLE
NavigationBar.apiLevel undefined

### ISSUE THREAD

**Issue by liudas-stonys** [BhavanPatel/react-native-navbar-color#5]
Thank you for this awesome patch, but I have a problem with NavigationBar.setColor("#bada55"). I get this error: TypeError: undefined is not an object (evaluating 'NavigationBar.apiLevel'). I'm using Expo, so maybe that is the problem or maybe it's just me being a noob... Please, help :)

I'm developing in Expo on Windows and run on Android 8 device.

**Comment by BhavanPatel** [comment]
Thank you for reporting issue. I will look into it and release next version as soon as possible. :)

**Comment by hadicahyadi** [comment]
Hi guys, is there any working solution for this issue ? i'm facing same issue

**Comment by BhavanPatel** [comment]
For Expo it won't work.

**Comment by shadowgroundz** [comment]
I use react-native cli. Same issue
